In [ ]:
# Load, Inspect and Clean

import pandas as pd
df = pd.read_csv("used_cars_messy.csv")
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0

In [13]:
df.shape

(15661, 14)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  str
 2   brand              15661 non-null  str
 3   model              15661 non-null  str
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  str
 6   seller_type        15661 non-null  str
 7   fuel_type          15661 non-null  str
 8   transmission_type  15661 non-null  str
 9   mileage            14376 non-null  str
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), str(8)
memory usage: 1.7 MB

In [10]:
df.isnull().sum()

Unnamed: 0              0
car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven               0
seller_type             0
fuel_type               0
transmission_type       0
mileage              1285
engine               1869
max_power             799
seats                 443
selling_price         158
dtype: int64

In [14]:
df.isnull().sum() * 100/ len(df)

Unnamed: 0            0.000000
car_name              0.000000
brand                 0.000000
model                 0.000000
vehicle_age           0.000000
km_driven             0.000000
seller_type           0.000000
fuel_type             0.000000
transmission_type     0.000000
mileage               8.205095
engine               11.934104
max_power             5.101845
seats                 2.828683
selling_price         1.008876
dtype: float64

In [15]:
# Drop rows where selling_price is missing

before = len(df)

df = df.dropna(subset=['selling_price'])
after = len(df)
print(f"Dropped {before-after} rows where selling price is missing")

Dropped 158 rows where selling price is missing

For columns mileage, engine, and max_power — strip any unit strings (e.g. "kmpl", "CC", "bhp"), convert to numeric using pd.to_numeric(..., errors='coerce'), and fill remaining nulls with each column's median.

In [16]:
df.columns

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'selling_price'],
      dtype='str')

In [17]:
print(type(df['mileage']))

<class 'pandas.Series'>

In [18]:
df['mileage'].head(100)

0     19.87
1     33.54
2       NaN
3      15.4
4      16.0
      ...
95     13.0
96     22.1
97     24.3
98     13.5
99     17.8
Name: mileage, Length: 100, dtype: str

In [21]:
df['mileage'] = df['mileage'].astype(str).str.replace('kmpl', '')
df['engine'] = df['engine'].astype(str).str.replace('CC', '')
df['max_power'] = df['max_power'].astype(str).str.replace('bhp', '')

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15503 non-null  int64
 1   car_name           15503 non-null  str
 2   brand              15503 non-null  str
 3   model              15503 non-null  str
 4   vehicle_age        15503 non-null  int64
 5   km_driven          15503 non-null  str
 6   seller_type        15503 non-null  str
 7   fuel_type          15503 non-null  str
 8   transmission_type  15503 non-null  str
 9   mileage            14234 non-null  str
 10  engine             13651 non-null  str
 11  max_power          14712 non-null  str
 12  seats              15065 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(2), int64(2), str(10)
memory usage: 1.8 MB

In [30]:
df['mileage'] = pd.to_numeric(df['mileage'], errors='coerce')
df['engine'] = pd.to_numeric(df['engine'], errors='coerce')
df['max_power'] = pd.to_numeric(df['max_power'], errors='coerce')

In [31]:
df.info()

<class 'pandas.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15503 non-null  int64
 1   car_name           15503 non-null  str
 2   brand              15503 non-null  str
 3   model              15503 non-null  str
 4   vehicle_age        15503 non-null  int64
 5   km_driven          15253 non-null  float64
 6   seller_type        15503 non-null  str
 7   fuel_type          15503 non-null  str
 8   transmission_type  15503 non-null  str
 9   mileage            14234 non-null  float64
 10  engine             13651 non-null  float64
 11  max_power          14712 non-null  float64
 12  seats              15065 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(6), int64(2), str(6)
memory usage: 1.8 MB

In [32]:
for col in ['engine', 'mileage', 'max_power']:
    median_val = df[col].median()
    df[col] = df[col].fillna(median_val)
    print(f"Filled {col} missing values with median: {median_val}")

Filled engine missing values with median: 1248.0
Filled mileage missing values with median: 19.67
Filled max_power missing values with median: 88.5

In [33]:
df.isnull().sum() * 100/ df.shape[0]

Unnamed: 0           0.000000
car_name             0.000000
brand                0.000000
model                0.000000
vehicle_age          0.000000
km_driven            1.612591
seller_type          0.000000
fuel_type            0.000000
transmission_type    0.000000
mileage              0.000000
engine               0.000000
max_power            0.000000
seats                2.825260
selling_price        0.000000
dtype: float64

In [34]:
# Remove rows where selling_price is 999999999 or below 10000

df = df[(df['selling_price'] >= 1000)]

In [35]:
df = df[df['selling_price'] != 999999999]

In [37]:
df.shape

(15495, 14)

In [38]:
df.info()

<class 'pandas.DataFrame'>
Index: 15495 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15495 non-null  int64
 1   car_name           15495 non-null  str
 2   brand              15495 non-null  str
 3   model              15495 non-null  str
 4   vehicle_age        15495 non-null  int64
 5   km_driven          15245 non-null  float64
 6   seller_type        15495 non-null  str
 7   fuel_type          15495 non-null  str
 8   transmission_type  15495 non-null  str
 9   mileage            15495 non-null  float64
 10  engine             15495 non-null  float64
 11  max_power          15495 non-null  float64
 12  seats              15057 non-null  float64
 13  selling_price      15495 non-null  float64
dtypes: float64(6), int64(2), str(6)
memory usage: 1.8 MB

Dropping duplicate rows

In [39]:
df.duplicated().sum()

np.int64(172)

In [40]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [41]:
df.shape

(15323, 14)

Encoding Categorical Features

In [42]:
df['transmission_type'] = df['transmission_type'].map({'Manual': 0, 'Automatic' : 1})
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647.0,Dealer,Diesel,0,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000.0,Dealer,CNG,0,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959.0,Dealer,Petrol,0,19.67,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000.0,dealer,Diesel,0,15.40,2179.0,88.50,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000.0,Dealer,Diesel,1,16.00,2179.0,140.00,7.0,1175000.0

In [43]:
df['fuel_type'].value_counts()

fuel_type
Petrol      7317
Diesel      7219
CNG          295
PETROL        67
 Petrol       65
petrol        61
petrol        55
Petrol        48
LPG           44
diesel        40
diesel        38
DIESEL        36
 Diesel       34
Electric       4
Name: count, dtype: int64

In [44]:
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647.0,Dealer,Diesel,0,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000.0,Dealer,CNG,0,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959.0,Dealer,Petrol,0,19.67,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000.0,dealer,Diesel,0,15.40,2179.0,88.50,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000.0,Dealer,Diesel,1,16.00,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731.0,Dealer,Diesel,0,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000.0,Dealer,Petrol,0,16.09,1248.0,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000.0,Individual,Petrol,0,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000.0,Dealer,Petrol,0,18.60,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000.0,Individual,Petrol,1,20.28,1462.0,103.25,5.0,960000.0

In [45]:
print(f"columns before one hot encoing {df.shape[1]}")

columns before one hot encoing 14

In [46]:
df['fuel_type'].unique()

<StringArray>
[  'Diesel',      'CNG',   'Petrol',  'Petrol ',   'DIESEL',  ' Petrol',
  'petrol ',   'PETROL',  ' Diesel',  'diesel ',      'LPG',   'petrol',
   'diesel', 'Electric']
Length: 14, dtype: str

In [47]:
df = pd.get_dummies(df, columns = ['fuel_type'], drop_first = True)
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,transmission_type,mileage,engine,...,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_PETROL,fuel_type_Petrol,fuel_type_Petrol,fuel_type_diesel,fuel_type_diesel,fuel_type_petrol,fuel_type_petrol
0,2581,Renault Duster,Renault,Duster,7,67647.0,Dealer,0,19.87,1461.0,...,True,False,False,False,False,False,False,False,False,False
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000.0,Dealer,0,33.54,998.0,...,False,False,False,False,False,False,False,False,False,False
2,1803,Honda City,Honda,City,3,48959.0,Dealer,0,19.67,1497.0,...,False,False,False,False,True,False,False,False,False,False
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000.0,dealer,0,15.40,2179.0,...,True,False,False,False,False,False,False,False,False,False
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000.0,Dealer,1,16.00,2179.0,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731.0,Dealer,0,20.77,1248.0,...,True,False,False,False,False,False,False,False,False,False
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000.0,Dealer,0,16.09,1248.0,...,False,False,False,False,True,False,False,False,False,False
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000.0,Individual,0,20.51,998.0,...,False,False,False,False,True,False,False,False,False,False
15659,1104,Hyundai i20,Hyundai,i20,2,15000.0,Dealer,0,18.60,1197.0,...,False,False,False,False,True,False,False,False,False,False
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000.0,Individual,1,20.28,1462.0,...,False,False,False,False,True,False,False,False,False,False

In [48]:
df['seller_type'].value_counts()

seller_type
Dealer              9399
Individual          5558
Trustmark Dealer     170
individual            44
Individuall           38
Individul             35
dealer                31
DEALER                28
Delaer                20
Name: count, dtype: int64

In [49]:
df = pd.get_dummies(df, columns = ['seller_type'], drop_first = True)
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,transmission_type,mileage,engine,max_power,...,fuel_type_petrol,fuel_type_petrol,seller_type_Dealer,seller_type_Delaer,seller_type_Individual,seller_type_Individuall,seller_type_Individul,seller_type_Trustmark Dealer,seller_type_dealer,seller_type_individual
0,2581,Renault Duster,Renault,Duster,7,67647.0,0,19.87,1461.0,83.80,...,False,False,True,False,False,False,False,False,False,False
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000.0,0,33.54,998.0,67.04,...,False,False,True,False,False,False,False,False,False,False
2,1803,Honda City,Honda,City,3,48959.0,0,19.67,1497.0,117.60,...,False,False,True,False,False,False,False,False,False,False
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000.0,0,15.40,2179.0,88.50,...,False,False,False,False,False,False,False,False,True,False
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000.0,1,16.00,2179.0,140.00,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731.0,0,20.77,1248.0,88.80,...,False,False,True,False,False,False,False,False,False,False
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000.0,0,16.09,1248.0,103.20,...,False,False,True,False,False,False,False,False,False,False
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000.0,0,20.51,998.0,67.04,...,False,False,False,False,True,False,False,False,False,False
15659,1104,Hyundai i20,Hyundai,i20,2,15000.0,0,18.60,1197.0,81.86,...,False,False,True,False,False,False,False,False,False,False
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000.0,1,20.28,1462.0,103.25,...,False,False,False,False,True,False,False,False,False,False

In [50]:
df[['seller_type_Individual', 'seller_type_Trustmark Dealer']]

       seller_type_Individual  seller_type_Trustmark Dealer
0                       False                         False
1                       False                         False
2                       False                         False
3                       False                         False
4                       False                         False
...                       ...                           ...
15656                   False                         False
15657                   False                         False
15658                    True                         False
15659                   False                         False
15660                    True                         False

[15323 rows x 2 columns]

In [51]:
df.columns.tolist()

['Unnamed: 0',
 'car_name',
 'brand',
 'model',
 'vehicle_age',
 'km_driven',
 'transmission_type',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price',
 'fuel_type_ Petrol',
 'fuel_type_CNG',
 'fuel_type_DIESEL',
 'fuel_type_Diesel',
 'fuel_type_Electric',
 'fuel_type_LPG',
 'fuel_type_PETROL',
 'fuel_type_Petrol',
 'fuel_type_Petrol ',
 'fuel_type_diesel',
 'fuel_type_diesel ',
 'fuel_type_petrol',
 'fuel_type_petrol ',
 'seller_type_Dealer',
 'seller_type_Delaer',
 'seller_type_Individual',
 'seller_type_Individuall',
 'seller_type_Individul',
 'seller_type_Trustmark Dealer',
 'seller_type_dealer',
 'seller_type_individual']

Why is drop_first=True used in one-hot encoding, and what does a row of all zeros in the new dummy columns represent?

In one-hot encoding, drop_first=True is used to avoid multicollinearity, also known as the dummy variable trap, where one dummy variable can be predicted from others. By dropping one category, it becomes the reference group, and the model uses it as a baseline for comparison. A row with all zeros in the dummy columns represents this dropped reference category, meaning the observation belongs to that category which was intentionally removed during encoding.

In [52]:
# Task 3

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import warnings

In [53]:
df = df.drop(columns=['Unnamed: 0', 'car_name', 'model'])
print(f"Shape after dropping: {df.shape}")
print(f"Remaining columns: {df.columns.tolist()}")

Shape after dropping: (15323, 30)
Remaining columns: ['brand', 'vehicle_age', 'km_driven', 'transmission_type', 'mileage', 'engine', 'max_power', 'seats', 'selling_price', 'fuel_type_ Petrol', 'fuel_type_CNG', 'fuel_type_DIESEL', 'fuel_type_Diesel', 'fuel_type_Electric', 'fuel_type_LPG', 'fuel_type_PETROL', 'fuel_type_Petrol', 'fuel_type_Petrol ', 'fuel_type_diesel', 'fuel_type_diesel ', 'fuel_type_petrol', 'fuel_type_petrol ', 'seller_type_Dealer', 'seller_type_Delaer', 'seller_type_Individual', 'seller_type_Individuall', 'seller_type_Individul', 'seller_type_Trustmark Dealer', 'seller_type_dealer', 'seller_type_individual']

In [55]:
X = df.drop(columns=['selling_price'])
y = df['selling_price']

print(f"Features: {X.shape[0]} rows × {X.shape[1]} columns")
print(f"Target: selling_price — ₹{y.min():,} to ₹{y.max():,}")
print(f"Target mean: ₹{y.mean():,.0f}, median: ₹{y.median():,.0f}")

Features: 15323 rows × 29 columns
Target: selling_price — ₹40,000.0 to ₹39,500,000.0
Target mean: ₹775,869, median: ₹555,000

In [56]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Train: {X_train.shape[0]} rows ({X_train.shape[0]/len(X)*100:.0f}%)")
print(f"Test:  {X_test.shape[0]} rows ({X_test.shape[0]/len(X)*100:.0f}%)")

Train: 12258 rows (80%)
Test:  3065 rows (20%)

In [57]:
numeric_cols = ['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']

scaler = StandardScaler()
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])

In [58]:
X_train

,brand,vehicle_age,km_driven,transmission_type,mileage,engine,max_power,seats,fuel_type_ Petrol,fuel_type_CNG,...,fuel_type_petrol,fuel_type_petrol,seller_type_Dealer,seller_type_Delaer,seller_type_Individual,seller_type_Individuall,seller_type_Individul,seller_type_Trustmark Dealer,seller_type_dealer,seller_type_individual
4159,Mahindra,0.982801,0.155310,0,-0.929869,-0.426056,-0.907904,2.067650,False,False,...,False,False,False,False,True,False,False,False,False,False
15521,Mahindra,-0.009526,0.371988,0,-0.919879,1.486683,0.954643,2.067650,False,False,...,False,False,False,False,True,False,False,False,False,False
15349,Mahindra,-0.340301,-0.324969,0,-0.382902,-0.528781,-0.432106,0.833975,False,False,...,False,False,True,False,False,False,False,False,False,False
12890,Maruti,-0.671076,0.340681,0,-0.545244,-0.169244,-0.468926,2.067650,False,True,...,False,False,True,False,False,False,False,False,False,False
9978,Maruti,-1.332627,-0.771096,0,0.381355,-0.530836,-0.436888,-0.399699,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5271,Mahindra,-0.009526,1.219637,0,-1.069733,1.112764,0.476454,2.067650,False,False,...,False,False,False,False,True,False,False,False,False,False
13704,Ford,-0.340301,-0.664028,0,-0.380404,-0.532890,-0.317340,-0.399699,False,False,...,False,False,False,False,True,False,False,False,False,False
5472,Honda,-0.009526,0.014091,0,1.352909,0.087569,-0.035209,-0.399699,False,False,...,False,False,False,False,True,False,False,False,False,False
871,Hyundai,0.652025,0.277804,0,1.078176,-0.689032,-0.719019,-0.399699,False,False,...,False,False,True,False,False,False,False,False,False,False
7384,Maruti,-1.332627,-0.795885,0,-1.077226,-0.532890,-0.647291,-0.399699,False,False,...,False,False,False,False,True,False,False,False,False,False

In [65]:
df = pd.get_dummies(df, columns=['brand'], drop_first=True)

In [68]:
df.info()

<class 'pandas.DataFrame'>
Index: 15323 entries, 0 to 15660
Columns: 108 entries, vehicle_age to brand_Volvo
dtypes: bool(100), float64(6), int64(2)
memory usage: 2.5 MB

In [69]:
X = df.drop(columns=['selling_price'])
y = df['selling_price']

print(f"Features: {X.shape[0]} rows × {X.shape[1]} columns")
print(f"Target: selling_price — ₹{y.min():,} to ₹{y.max():,}")
print(f"Target mean: ₹{y.mean():,.0f}, median: ₹{y.median():,.0f}")

Features: 15323 rows × 107 columns
Target: selling_price — ₹40,000.0 to ₹39,500,000.0
Target mean: ₹775,869, median: ₹555,000

In [71]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Train: {X_train.shape[0]} rows ({X_train.shape[0]/len(X)*100:.0f}%)")
print(f"Test:  {X_test.shape[0]} rows ({X_test.shape[0]/len(X)*100:.0f}%)")

Train: 12258 rows (80%)
Test:  3065 rows (20%)

In [72]:
numeric_cols = ['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']

scaler = StandardScaler()
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])

In [74]:
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])

In [75]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Train: {X_train.shape[0]} rows ({X_train.shape[0]/len(X)*100:.0f}%)")
print(f"Test:  {X_test.shape[0]} rows ({X_test.shape[0]/len(X)*100:.0f}%)")

Train: 12258 rows (80%)
Test:  3065 rows (20%)

In [77]:
X = df.drop(columns=['selling_price'])
y = df['selling_price']

print(f"Features: {X.shape[0]} rows × {X.shape[1]} columns")
print(f"Target: selling_price — ₹{y.min():,} to ₹{y.max():,}")
print(f"Target mean: ₹{y.mean():,.0f}, median: ₹{y.median():,.0f}")

Features: 15323 rows × 107 columns
Target: selling_price — ₹40,000.0 to ₹39,500,000.0
Target mean: ₹775,869, median: ₹555,000

In [78]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Train: {X_train.shape[0]} rows ({X_train.shape[0]/len(X)*100:.0f}%)")
print(f"Test:  {X_test.shape[0]} rows ({X_test.shape[0]/len(X)*100:.0f}%)")

Train: 12258 rows (80%)
Test:  3065 rows (20%)

In [82]:
X_train

,vehicle_age,km_driven,transmission_type,mileage,engine,max_power,seats,fuel_type_ Petrol,fuel_type_CNG,fuel_type_DIESEL,...,brand_Skoda,brand_Skoda,brand_Tata,brand_Tata,brand_Toyota,brand_Toyota,brand_Volkswagen,brand_Volkswagen,brand_Volvo,brand_Volvo
4159,9,63497.0,0,15.96,1248.0,62.10,7.0,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15521,6,75000.0,0,16.00,2179.0,140.00,7.0,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15349,5,38000.0,0,18.15,1198.0,82.00,6.0,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12890,4,73338.0,0,17.50,1373.0,80.46,7.0,False,True,False,...,False,False,False,False,False,False,False,False,False,False
9978,2,14316.0,0,21.21,1197.0,81.80,5.0,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5271,6,120000.0,0,15.40,1997.0,120.00,7.0,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13704,5,20000.0,0,18.16,1196.0,86.80,5.0,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5472,6,56000.0,0,25.10,1498.0,98.60,5.0,False,False,False,...,False,False,False,False,False,False,False,False,False,False
871,8,70000.0,0,24.00,1120.0,70.00,5.0,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7384,2,13000.0,0,15.37,1196.0,73.00,5.0,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [84]:
df = df.dropna()

In [85]:
df

,vehicle_age,km_driven,transmission_type,mileage,engine,max_power,seats,selling_price,fuel_type_ Petrol,fuel_type_CNG,...,brand_Skoda,brand_Skoda,brand_Tata,brand_Tata,brand_Toyota,brand_Toyota,brand_Volkswagen,brand_Volkswagen,brand_Volvo,brand_Volvo
0,7,67647.0,0,19.87,1461.0,83.80,5.0,575000.0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,3,52000.0,0,33.54,998.0,67.04,5.0,435000.0,False,True,...,False,False,False,False,False,False,False,False,False,False
2,3,48959.0,0,19.67,1497.0,117.60,5.0,875000.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,6,82000.0,0,15.40,2179.0,88.50,8.0,925000.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4,4,34000.0,1,16.00,2179.0,140.00,7.0,1175000.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,7,127731.0,0,20.77,1248.0,88.80,7.0,665000.0,False,False,...,False,False,False,False,False,False,False,False,False,False
15657,11,59000.0,0,16.09,1248.0,103.20,5.0,249000.0,False,False,...,False,False,False,False,False,False,True,False,False,False
15658,7,20000.0,0,20.51,998.0,67.04,5.0,250000.0,False,False,...,False,False,False,False,False,False,False,False,False,False
15659,2,15000.0,0,18.60,1197.0,81.86,5.0,620000.0,False,False,...,False,False,False,False,False,False,False,False,False,False
15660,2,30000.0,1,20.28,1462.0,103.25,5.0,960000.0,False,False,...,False,False,False,False,False,False,False,False,False,False

In [86]:
df.shape

(14654, 108)

In [89]:
df.isnull().sum().sum()

np.int64(0)

In [92]:
X = df.drop(columns=['selling_price'])
y = df['selling_price']

print(f"Features: {X.shape[0]} rows × {X.shape[1]} columns")
print(f"Target: selling_price — ₹{y.min():,} to ₹{y.max():,}")
print(f"Target mean: ₹{y.mean():,.0f}, median: ₹{y.median():,.0f}")

Features: 14654 rows × 107 columns
Target: selling_price — ₹40,000.0 to ₹39,500,000.0
Target mean: ₹775,377, median: ₹555,000

In [93]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Train: {X_train.shape[0]} rows ({X_train.shape[0]/len(X)*100:.0f}%)")
print(f"Test:  {X_test.shape[0]} rows ({X_test.shape[0]/len(X)*100:.0f}%)")

Train: 11723 rows (80%)
Test:  2931 rows (20%)

In [94]:
numeric_cols = ['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']

scaler = StandardScaler()
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])

In [95]:
X_train

,vehicle_age,km_driven,transmission_type,mileage,engine,max_power,seats,fuel_type_ Petrol,fuel_type_CNG,fuel_type_DIESEL,...,brand_Skoda,brand_Skoda,brand_Tata,brand_Tata,brand_Toyota,brand_Toyota,brand_Volkswagen,brand_Volkswagen,brand_Volvo,brand_Volvo
4199,-0.341475,-0.286557,0,-0.922557,1.493222,0.955963,2.068109,False,False,False,...,False,False,False,False,False,False,False,False,False,False
799,-0.341475,-0.469966,0,-0.546194,-0.318441,-0.338067,-0.405309,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7304,-0.341475,-0.469966,0,-0.623976,-0.526135,-0.432135,-0.405309,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10268,0.326322,0.043581,0,0.758529,0.092833,-0.241612,-0.405309,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8235,0.994120,-0.007114,0,-0.144741,-0.526135,-0.338067,-0.405309,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5507,-1.343171,-0.469966,0,2.188706,-0.421260,-0.619315,-0.405309,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14354,-0.675374,-0.726740,0,0.836310,-0.933297,-0.786919,-0.405309,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5711,0.660221,-0.580012,1,-0.001723,3.167109,5.086354,-1.642018,False,False,False,...,False,False,False,False,False,False,False,False,False,False
917,-0.341475,0.025240,0,-0.623976,-0.421260,-0.432135,-0.405309,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7710,-0.675374,-0.414943,0,1.159982,-0.421260,-0.273604,-0.405309,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [96]:
model = LinearRegression()
model.fit(X_train, y_train)

print(f"Model trained ✅")
print(f"Number of coefficients: {len(model.coef_)}")
print(f"Intercept: ₹{model.intercept_:,.0f}")

Model trained ✅
Number of coefficients: 107
Intercept: ₹3,765,431

In [97]:
model.coef_

array([-2.41908678e+05, -3.06148189e+04,  6.87167494e+04, -3.24099239e+04,
        1.45058431e+05,  2.64203699e+05,  2.25522275e+04, -8.36425779e+04,
       -4.03210731e+04, -9.51035765e+04,  2.45510834e+04,  4.74118678e+05,
        2.20108005e+05, -1.14199364e+05, -5.61137940e+04,  3.19685681e+04,
        2.76297043e+04,  1.12842618e+04, -4.58638912e+04, -9.53607028e+04,
        1.90078176e+05,  1.64101723e+05,  1.68689081e+05,  1.68531161e+05,
        1.94373999e+05,  9.82976434e+04,  2.03975845e+05,  1.88599433e+05,
       -3.55711689e+06, -1.65616701e+06,  2.15814381e+06, -3.43814480e+06,
       -3.25605766e+06,  3.12103606e+07, -3.27852078e+06, -3.22735561e+06,
       -3.27072009e+06, -3.32150256e+06, -3.22452402e+06, -3.31204113e+06,
       -3.34597998e+06,  1.77175749e+06,  1.95577741e-08, -3.44336602e+06,
       -3.41644588e+06, -3.19431526e+06, -3.18814649e+06, -1.21702103e+06,
       -3.22952893e+06, -2.29372886e+06, -9.54605639e-09, -8.61473382e-09,
       -3.28607273e+06, -3.20754269e+06, -3.48193551e+06, -3.55510882e+06,
       -3.23258601e+06, -3.29812948e+06, -3.29752246e+06, -3.15880071e+06,
       -3.34349099e+06, -3.35192083e+06, -2.58607946e+06, -2.83184272e+06,
       -2.17171234e+06, -1.95694326e+06,  1.49066966e+06, -3.37546596e+06,
       -1.86264515e-09, -3.57158276e+06, -3.27750608e+06, -3.33456978e+06,
       -3.29900355e+06, -3.29921427e+06, -3.24733276e+06, -3.27251767e+06,
        1.16415322e-09, -3.38443841e+06, -2.22403282e+06, -2.89037104e+06,
       -2.74316046e+06, -1.20546208e+06, -2.49998370e+05, -3.00704306e+06,
       -3.45992802e+06, -3.55447629e+06, -3.18037409e+06, -3.13729895e+06,
        3.12453192e+05, -2.28565170e+06, -3.29780748e+06, -2.14938338e+06,
       -3.39663076e+06, -5.72786163e+05, -3.30647969e+06, -3.69770230e+06,
        1.86264515e-09, -3.31929544e+06, -3.59072202e+06, -3.49052502e+06,
       -3.42421485e+06, -3.13944379e+06, -3.09069803e+06, -3.29951890e+06,
       -3.55129088e+06, -8.20688954e+05,  0.00000000e+00])

In [98]:
# Predictions on both sets
y_train_pred = model.predict(X_train)
print(y_train_pred)

[1135836.15637457  667676.65347454  548258.09148926 ... 3501383.04495954
  569699.54448195  787866.26981026]

In [99]:
print(y_train)

4199     1150000.0
799       600000.0
7304      525000.0
10268     475000.0
8235      350000.0
           ...
5507      780000.0
14354     315000.0
5711     4000000.0
917       590000.0
7710      675000.0
Name: selling_price, Length: 11723, dtype: float64

In [100]:
# Metrics on TRAIN
train_mae = mean_absolute_error(y_train, y_train_pred)
print(train_mae)

207073.96751525547

In [101]:
y_test_pred = model.predict(X_test)
test_mae = mean_absolute_error(y_test, y_test_pred)
print(test_mae)

1472216125.8605957

In [102]:
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])
y_test_pred = model.predict(X_test)
test_mae = mean_absolute_error(y_test, y_test_pred)
print(test_mae)

212311.94061837136

In [103]:
df['selling_price'].mean()

np.float64(775377.2945953324)

In [104]:
df['base_pred'] = 774971.1164103562

In [105]:
base_mae = mean_absolute_error(df['selling_price'], df['base_pred'])
print(base_mae)

453539.2883965957

In [107]:
base_mae_rounded = round(base_mae)
print("BASE_MAE (₹):", base_mae_rounded)

BASE_MAE (₹): 453539